### ISSUE TITLE
Example that doesn't directly refer to alcohol?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [stryker-mutator/stryker-mutator.github.io#713]
https://stryker-mutator.io/docs/General/example -> https://github.com/stryker-mutator/robobar-example is a great demo app for Stryker. But the theme is a bar serving alcoholic drinks (beer, wine). That can be hard for some folks in tech to see, such as recovering alcoholics.

Would you be open to changing the theme to something less booze-related? My default suggestion would be something vegan like a boba tea shop.

I'd be happy to send a PR!

**Comment by rouke-broersma** [comment]
@JoshuaKGoldberg ideally the example shows a clear edge case that speaks to the audience and is a real world example. I can't think of anything that is more universally recognizable than an age limit but an age limit doesn't make sense for boba tea. 

Also genuinely curious since I'm not personally familiar with this being an issue, is this something that has been brought up to you before or is this preemptive?

Are references like 'free as in beer' also a problem?

**Comment by JoshuaKGoldberg** [comment]
Thank you for the kind response Rouke! I was a little nervous posting this, and it's a relief to get back an inquisitive response like yours. ❤️ 

> I can't think of anything that is more universally recognizable than an age limit but an age limit doesn't make sense for boba tea

Yeah, it's hard to think of a >= as good example. The first alternative that comes to mind for me is whether the user is a vegetarian, and having some menu items that include meat? Or, alternately, a menu item with hot sauce that requires a disclaimer?

I tried out a fork here: https://github.com/JoshuaKGoldberg/robocafe-example. It replaces "bar" with "cafe" and switches the numeric age input+check with a boolean vegetarian input+check.

> is this something that has been brought up to you before or is this preemptive?

It's been brought up. It's not a problem for me personally, but I know multiple people in the greater dev community who have experienced personal trauma around alcohol. Many of them have indicated that while an alcohol theme isn't isn't a blocker for them, it's at least a little unpleasant. 

There are two main points against including alcohol that resonate with me:

* Potential triggers: e.g. for recovering alcoholics. Everyone is different and has different tolerances for references to alcohol, but as a general courtesy, it can be good to not unnecessarily bring it up.
* Contextual restrictions: e.g. for schools that can't include references to controlled substances as a matter of policy. If we wanted to show Stryker to, say, most high schools in the United States, we'd have to find a different example.

I know the question of _"where do we draw the line?"_ for which potential triggers to avoid can be contentious. Personally, I have found that alcohol goes over where many folks would want to draw that line. But at the very least I'd think the _contextual restrictions_ point is minimally enough to justify moving to a different example.

_(Disclaimer: I am not an expert in this space. I may be inaccurate in how I'm phrasing the points. Don't take my statements to represent any other people or groups!)_

> Are references like 'free as in beer' also a problem?

Great question. To a lesser extent, yes. Same reasoning. There's no need to specifically refer to beer, other than the existing context and history for the quote. If the open source community had started by saying _'free as in tea'_ then the phrase would have about the same intent and meaning, without the link to alcohol. 

---

Edit: I'm getting paranoid that this is coming across as me trying to speak naively for a group of people. So adding in personal context: someone close to me is an addict for a substance that, like alcohol, is commonly referenced in culture. They of course can handle it being used as a theme in places, but it's a little unpleasant for them. It reminds them of the substance and can sometimes contribute to existing mental cycling on their end. They prefer themes that don't involve the substance (it comes up surprisingly often) as a courtesy. This post here is in line with what they've asked of me and others. The _potential triggers_ point I'd like to make is that although it may not be _necessary_ to completely avoid alcohol as a theme, it's at least _preferable_ in this context.

**Comment by hugo-vrijswijk** [comment]
I asked ChatGPT for some ideas. Most of them were bad. But some might work:

- Social services eligibility. Enter your income, and below a certain threshold (say, €15.000, like ~here in the Netherlands) you're eligible for social services. "Bug" would be the check should be `<` but uses `<=`. The downside is it's not as clear to me because requires precise input and knowledge of the threshold. Plus Americans might be put off by socialism 😉
- Shopping cart. Orders from €50,- get free shipping. But exactly €50,- somehow doesn't qualify. This is also a bit finicky as it would require users to precisely add products until it adds up to €50,-. 
- Something similar, but with maximum luggage weight for a flight
- Meeting room booking system. Enter how many people you want to book a room for, and it filters rooms that are big enough (but off-by-one due to `<=`/`<`). Maybe not as cool as a robobar.

**Comment by rouke-broersma** [comment]
@JoshuaKGoldberg 
> Thank you for the kind response Rouke! I was a little nervous posting this, and it's a relief to get back an inquisitive response like yours. ❤️

To be honest my initial gut reaction was _really, this is also an issue now_ but since I have no personal experience to draw from I thought it would be best to just be open minded.

> I tried out a fork here: https://github.com/JoshuaKGoldberg/robocafe-example. It replaces "bar" with "cafe" and switches the numeric age input+check with a boolean vegetarian input+check.

I don't like the idea of switching to a boolean example because it's too obvious of a mistake instead of an accidental oversight. It might make people think they would never make the mistake.
 
> Edit: I'm getting paranoid that this is coming across as me trying to speak naively for a group of people.

No worries I was purposefully avoiding asking directly because frankly it's none of my business, only wanted to differentiate between 'might potentially be a problem maybe' and 'there are actual real life people affected by this'.

@hugo-vrijswijk 

RoboRollerCoasters instead of RoboBar.

How about a theme park (or other 'experience') where you have adult or children tickets depending on the age? We could also for example have additional tickets for specific rides where you have to be a certain age to be allowed purchasing a ticket at all. It would extend our example to both a allow/deny and a wrong total at checkout scenario.

**Comment by JoshuaKGoldberg** [comment]
I love it, thanks! Will send a PR Soon™️ if nobody else does.

> RoboRollerCoasters

Or... RoboCoasters? 😄

**Comment by nicojs** [comment]
+1 for RoboCoasters.

@JoshuaKGoldberg are you still planning on picking this up? If you want I would like to help. I'm giving a talk on Feb 4th and would love a new example. 😻

**Comment by JoshuaKGoldberg** [comment]
Yes, thank you! I'd marked this as "pending confirmation of 'RoboCoasters'" in my todo list. Can tackle this week!

**Comment by riezebosch** [comment]
> How about a theme park (or other 'experience') where you have adult or children tickets depending on the age? We could also for example have additional tickets for specific rides where you have to be a certain age to be allowed purchasing a ticket at all. It would extend our example to both a allow/deny and a wrong total at checkout scenario.

or height, since that's usually measured (in NL) when trying to enter a specific ride.
