### ISSUE TITLE
Remove generated files from repo

### ISSUE THREAD

**Issue by hugo-vrijswijk** [stryker-mutator/stryker-mutator.github.io#79]
Remove all generated files from the repo to reduce confusion

**Comment by kmdrGroch** [comment]
@hugo-vrijswijk I suppose it is served using github pages so these files need to be there .

**Comment by hugo-vrijswijk** [comment]
We could have two separate branches. One for development where no generated files are. Then a master branch that only the build-bot pushes built files to on a push in the development branch

**Comment by nicojs** [comment]
> Alternatively, we could also move the generated files to the docs/ folder and set that as the base for the github pages, just to clean it up a little

Are you referring to [https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/#publishing-your-github-pages-site-from-a-docs-folder-on-your-master-branch](https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/#publishing-your-github-pages-site-from-a-docs-folder-on-your-master-branch)? We cannot use this because it is the organizations main github.io page: 

> To publish your site's source files from a /docs folder on your master branch, you must have a master branch and your repository must:
    * have a /docs folder in the root of the repository
    * **not follow the repository naming scheme <username>.github.io or <orgname>.github.io**

That leaves us with option 1. It is definitely possible, although I would need to do some experiments. It would go something like this:

* Create a develop branch
* Add all output files to `.gitignore` and remove them from disk, commit that
* Configure a travis build that builds the site. 
* Add an `after_success` script that:
    * Checks to see if the current branch is `develop` and that it is **NOT** a pull request
    * If so, read a github API key configured as travis secret and configure on a new remote
    * Checkout the master branch while somehow preserving the files we just build
    * Commit and push those files to the root of the master branch

As an optimization for local development,  on the `develop` branch, we could configure grunt so all build files land in a `dist` folder, so we don't have to look at those files in the root of our repository.

**Comment by kmdrGroch** [comment]
@nicojs and it would solve #64.

**Comment by nicojs** [comment]
Yep, it's a duplicate. I will close that one :)

**Comment by nicojs** [comment]
I've started work on this. In the redesign branch all generated files are already removed.

**Comment by hugo-vrijswijk** [comment]
Should we set up a build that builds the latest in a specified branch (develop?) and pushes it to master?

**Comment by nicojs** [comment]
I'm closing this issue for now. Generated files are gone
